version: "2"

services:
  web:
    build: . # 현재 경로에 이미지 빌드
    ports: 
      - "3000:3000" #포트 포워딩
    image: nodejs-server
    volumes: 
      - ./src:/app/src:ro
      # 호스트 머신의 현재 작업 디렉토리 내의 src 폴더를 컨테이너 내부의 /app/src 경로에 읽기 전용으로 마운트
      #호스트 데이터를 컨테이너에게 공유
    networks:
      - testnet

networks:
  testnet:
    external: true 
    # 기존에 생성된 network 사용
    # 해당 옵션 없이 정의만 하면 디렉터리명 + 작성한 이름의 새로운 Network 생성

    